openapi: 3.0.1
info:
  title: product-service
  version: 0.0.1
security:
  - type: [OAuth2]
paths:
  /api/screenscraping/importHotels:
    post:
      tags:
        - ScreenScraping
      description: Fetch hotels data and insert into database
      operationId: importHotels
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenScrapingHotelSearchRequest'
        required: true
      responses:
        200:
          description: Inserted hotels info into database
          content: {}
        error:
          $ref: '#/components/responses/DefaultResponse'

components:
  schemas:
    Problem:
      type: object
      properties:
        type:
          type: string
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          format: uri
          default: about:blank
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          maximum: 6E+2
          exclusiveMaximum: true
          minimum: 1E+2
          type: integer
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          format: int32
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
    ScreenScrapingHotelSearchRequest:
      type: object
      properties:
        hotelname:
          type: string
          example: A Victory Inn & Suites
        country:
          type: string
          example: United States of America
        city:
          type: string
          example: Detroit
        state:
          type: string
          example: MI
        zip:
          type: string
          example: 48219

  responses:
    DefaultResponse:
      description: Something went wrong. Applicable for all errors returned by API (4xx, 5xx, etc)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://automatically/replaced/on/runtime
          scopes: {}
