/*
 * This file is generated by jOOQ.
 */
package com.gen.jooq;


import com.gen.jooq.tables.TableDatabasechangelog;
import com.gen.jooq.tables.TableDatabasechangeloglock;
import com.gen.jooq.tables.TableScreenScrapingAuthentication;
import com.gen.jooq.tables.TableScreenScrapingHotels;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final TableDatabasechangelog DATABASECHANGELOG = TableDatabasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final TableDatabasechangeloglock DATABASECHANGELOGLOCK = TableDatabasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.screen_scraping_authentication</code>.
     */
    public static final TableScreenScrapingAuthentication SCREEN_SCRAPING_AUTHENTICATION = TableScreenScrapingAuthentication.SCREEN_SCRAPING_AUTHENTICATION;

    /**
     * The table <code>public.screen_scraping_hotels</code>.
     */
    public static final TableScreenScrapingHotels SCREEN_SCRAPING_HOTELS = TableScreenScrapingHotels.SCREEN_SCRAPING_HOTELS;
}
